<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Generate password_pass1</name>
   <tag></tag>
   <elementGuidId>7f514f4d-7c61-494c-88bd-91d5ff083cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pass1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pass1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e8cffef-f5a6-4daf-b6f3-18ea46de6e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16aaeb99-0cf6-4dd8-8fa4-de3dc2422318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pass1</value>
      <webElementGuid>96cc50e9-4107-4173-8dfc-cab09f49ebdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pass1</value>
      <webElementGuid>b281deeb-f486-4a90-a194-a5c63cf48f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regular-text strong</value>
      <webElementGuid>7f4e20aa-540b-4e65-9520-8fbbe160ee27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>ab9b9481-d114-4014-86d8-46d4b073b888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>77d50f41-bbca-463d-b9f3-81cb1320e31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reveal</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>299c351f-b966-449c-9383-bdf25eed7122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pw</name>
      <type>Main</type>
      <value>JV3dlC!jokmcW@5&amp;PYowS&amp;%H</value>
      <webElementGuid>fc47a185-15c9-40b4-96f3-e2495a43de93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>pass-strength-result</value>
      <webElementGuid>26fd7656-d766-48eb-97e8-221a8c0b58bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pass1&quot;)</value>
      <webElementGuid>1d89272d-934a-459d-b7cc-f4c1b3d021db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pass1']</value>
      <webElementGuid>9de82fed-601a-4a59-b361-1d518739f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createuser']/table/tbody/tr[7]/td/div/div/input</value>
      <webElementGuid>757cca56-3263-46c4-976f-d3b07268cca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0a629788-e334-4bda-8057-731d99a32b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pass1' and @id = 'pass1']</value>
      <webElementGuid>ceb805d0-f617-4f63-82f8-41ae07573cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
