<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>ba4b97d8-5a81-4aea-ade0-ebe86bba6e79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Delete')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.submitdelete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f263fb1-8d0d-41c4-b95a-d80b4e96b3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submitdelete</value>
      <webElementGuid>75d523b6-6dd5-41a8-8baf-cad3da338f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>users.php?action=delete&amp;user=2&amp;_wpnonce=8199690832</value>
      <webElementGuid>26c485a9-836f-465e-8aaf-27ce2095f652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>fe4dacbb-a7e7-4401-bdc3-8420ffe10a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-2&quot;)/td[@class=&quot;username column-username has-row-actions column-primary&quot;]/div[@class=&quot;row-actions visible&quot;]/span[@class=&quot;delete&quot;]/a[@class=&quot;submitdelete&quot;]</value>
      <webElementGuid>599ddb96-f979-4486-b1ff-627ce1093fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='user-2']/td/div/span[2]/a</value>
      <webElementGuid>ae083944-3273-432c-b5a1-71384a1e309f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Delete')]</value>
      <webElementGuid>f7369c68-ccc8-4dc5-9b65-aeea8d6dba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/following::a[1]</value>
      <webElementGuid>5128c7a7-6cc6-440f-b7e1-f523c2933037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[3]/preceding::a[1]</value>
      <webElementGuid>aad4a70e-2ea4-41fa-a0a9-a317ac6cb66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'users.php?action=delete&amp;user=2&amp;_wpnonce=8199690832')]</value>
      <webElementGuid>e55aa965-bb97-4b2b-a7cf-4c445955c678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/span[2]/a</value>
      <webElementGuid>8ecf677b-62ac-4725-a60f-2bee8980503e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'users.php?action=delete&amp;user=2&amp;_wpnonce=8199690832' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>c804a12f-fba9-49a0-89fb-f6dd8da1472b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
